language: java

env:
  matrix:
    #- SPRING_PROFILES_ACTIVE=test
    - SPRING_PROFILES_ACTIVE=travis
  global:
    - MAVEN_OPTS='-Xss256k'
    - secure: "fBav56BzY+A+Vs1g9YSfo1oLDCO1rFrXl49lJkOA5/XpnsKEEs4lI2RcOzz0wiJKXFNgcliiAJWoYMI8Esqz+lkyFWan4ij5Co0UzJcytDuY+2o+jaqwx45DuDYPogABzT+hWjLCxQLLG46gUkChzT8kcvOOn6JxC7Ff8q5MnoM="

before_script:
  - set -o errexit # exit immediately when commands return a non-zero status
  - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
      mysql -u root -e 'CREATE DATABASE mystamps CHARACTER SET utf8;';
      mysql -u root -e "GRANT ALL PRIVILEGES ON mystamps.* TO 'travis'@'%';";
      mkdir -p /tmp/uploads /tmp/preview;
      cp src/main/resources/test/test.png /tmp/uploads/1.png;
      if [ "$TRAVIS_BRANCH" = 'prod' -a "$TRAVIS_PULL_REQUEST" = 'false' ]; then
        pip install --user ansible==2.1.1.0;
      fi;
      npm install -g bootlint;
      pip install --user html5validator;
      pip install --user robotframework-lint;
      if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
        gem install danger nokogiri --no-ri --no-rdoc;
      fi;
    fi

script:
  #- set -o errexit # exit immediately when commands return a non-zero status
  # run all check analysis and unit tests only on travis profile
  - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
      ./src/main/scripts/ci/check-build-and-verify.sh;
    fi
  # run integration tests always
  - ./src/main/scripts/ci/check-build-and-verify.sh --only-integration-tests;

after_failure:
  - mysql -u travis --database mystamps -e "SELECT * FROM countries;";
  # In order to be able debug robot framework test flakes we need to have a report.
  # Just encode it to a gzipped binary form and dump to console.
  - if fgrep -qs 'status="FAIL"' target/robotframework-reports/output.xml; then
      echo '===== RobotFramework report START =====';
      cat target/robotframework-reports/output.xml | gzip -c | base64 >robot-report.b64;
      print_with_delay robot-report.b64;
      echo '===== RobotFramework report END =====';
      rm -f robot-report.b64;
    fi
  # show MySQL error log only when we were running against MySQL database
  - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
      source ./src/main/scripts/ci/common.sh;
      sudo chmod +r /var/log/mysql/error.log;
      echo '===== MySQL error log START =====';
      print_with_delay /var/log/mysql/error.log;
      echo '===== MySQL error log END =====';
    fi

after_success:
  - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
      ./src/main/scripts/ci/publish-code-coverage.sh;
    fi

deploy:
  provider: script
  script: ./src/main/scripts/ci/deploy.sh
  on:
    branch: prod
    condition: '"$SPRING_PROFILES_ACTIVE" = "travis" && "$TRAVIS_PULL_REQUEST" = "false"'
  skip_cleanup: true

jdk:
  - oraclejdk8

services:
  - mysql

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

# We don't want to run `mvn install -DskipTests=true` for downloading project's dependencies
install: true
