---
- hosts: all
  gather_facts: no
  vars:
    profile: 'test'
    user_db_password: 'q1'
    user_mail_password: 'q2'
    # required for Ubuntu 16.04. which installs Python 2.x to a non-standard path
    ansible_python_interpreter: "/usr/bin/python2.7"

  pre_tasks:

  - name: Bootstrapping server
    include: bootstrap.yml

  - name: Removing nano
    apt:
      package: nano
      state: absent

  - name: Creating /data directory
    file:
      path: /data
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes
    become_method: sudo

  roles:
  - role: php-coder.oraclejdk
    become: yes
    become_method: sudo

  - role: mystamps-user
    become: yes
    become_method: sudo

  - role: mystamps-app
    become: yes
    become_method: sudo

  - {
      role: php-coder.nginx,
      remove_default_vhost: yes,
      state: stopped,
      become: yes,
      become_method: sudo
    }

  - role: mystamps-nginx
    become: yes
    become_method: sudo

  - {
      role: mystamps-backup,
      when: profile == 'prod',
      become: yes,
      become_method: sudo
    }
