---

- name: Uploading mystamps.war to a server
  copy:
    src: ../../target/mystamps.war
    dest: /data/mystamps/mystamps.war
    force: yes
    backup: no
    owner: mystamps
    group: mystamps
    mode: '0700'
  notify:
  - Restarting mystamps service

- name: Creating init-script
  file:
    src: /data/mystamps/mystamps.war
    dest: /etc/init.d/mystamps
    state: link

- name: Creating /data/logs
  file:
    path: /data/logs
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory

- name: Creating /data/uploads
  file:
    path: /data/uploads
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory
  when: profile == 'prod'

- name: Running service
  service:
    name: mystamps
    enabled: yes
    state: started

