---

- name: Uploading mystamps.war to a server
  copy:
    src: ../../target/mystamps.war
    dest: /data/mystamps/mystamps.war
    force: yes
    backup: no
    owner: mystamps
    group: mystamps
    mode: '0700'
  notify:
  - Restarting mystamps service

- name: Creating init-script
  file:
    src: /data/mystamps/mystamps.war
    dest: /etc/init.d/mystamps
    state: link

- name: Creating /data/logs
  file:
    path: /data/logs
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory

- name: Creating /data/uploads
  file:
    path: /data/uploads
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory
  when: profile == 'prod'

- name: Creating /data/heap-dumps
  file:
    path: /data/heap-dumps
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory
  when: profile == 'prod'

- name: Creating /data/mystamps/config
  file:
    path: /data/mystamps/config
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory
  when: profile == 'prod'

- name: Creating application-prod.properties
  template:
    src: application-prod.properties
    dest: /data/mystamps/config/application-prod.properties
    force: yes
    backup: no
    owner: mystamps
    group: mystamps
    mode: '0600'
  notify:
  - Restarting mystamps service
  when: profile == 'prod'

- name: Creating mystamps.conf
  copy:
    src: mystamps.conf
    dest: /data/mystamps/mystamps.conf
    mode: '0644'
  notify:
  - Restarting mystamps service
  when: profile == 'prod'

- name: Running service
  service:
    name: mystamps
    enabled: yes
    state: started

